import * as vscode from "vscode";

let activePanel: vscode.WebviewPanel | undefined;

/**
 * Opens an HTML file (typically generated by `deepsyte check --report html`)
 * in a WebView panel so users can review CI audit reports inside the editor
 * instead of jumping to a browser.
 */
export const HtmlReportPanel = {
  show(uri: vscode.Uri, html: string): void {
    if (activePanel) {
      activePanel.title = `Report: ${uri.path.split(/[\\/]/).pop() ?? "report.html"}`;
      activePanel.webview.html = html;
      activePanel.reveal(vscode.ViewColumn.Beside);
      return;
    }
    const panel = vscode.window.createWebviewPanel(
      "deepsyte.htmlReport",
      `Report: ${uri.path.split(/[\\/]/).pop() ?? "report.html"}`,
      vscode.ViewColumn.Beside,
      { enableScripts: false, retainContextWhenHidden: true },
    );
    panel.webview.html = html;
    panel.onDidDispose(() => {
      activePanel = undefined;
    });
    activePanel = panel;
  },
};
