/**
 * Pure formatters for `screenshotsmcp check` reports.
 * Kept separate so they're easy to unit-test and so `check.ts` stays focused
 * on orchestration.
 */

export interface UrlReport {
  url: string;
  ok: boolean;
  findings: number;
  categories: Record<string, number>;
  error?: string;
  /** Public CDN URL of the hero screenshot returned by `ux_review`. */
  imageUrl?: string;
}

export interface ReportContext {
  totalFindings: number;
  maxPer: number;
  maxTotal: number;
  pass: boolean;
  budgetSource?: string;
}

/**
 * Renders a markdown summary suitable for GitHub Actions comments or PR
 * descriptions. Includes a verdict header, a stat block, and a per-URL table.
 */
export function renderGithubComment(report: UrlReport[], ctx: ReportContext): string {
  const verdict = ctx.pass ? "\u2705 Passed" : "\u274C Failed";
  const lines: string[] = [];
  lines.push(`### ScreenshotsMCP audit \u2014 ${verdict}`);
  lines.push("");
  lines.push(`- **${report.length}** URL${report.length === 1 ? "" : "s"} audited`);
  lines.push(`- **${ctx.totalFindings}** total findings (limit \`${ctx.maxTotal}\`)`);
  lines.push(`- **${countFailed(report)}** URL${countFailed(report) === 1 ? "" : "s"} over the per-URL limit (\`${ctx.maxPer}\`)`);
  if (ctx.budgetSource) {
    lines.push(`- Budget loaded from \`${ctx.budgetSource}\``);
  }
  lines.push("");
  const anyImage = report.some((r) => r.imageUrl);
  if (anyImage) {
    lines.push("| URL | Status | Findings | Top categories | Preview |");
    lines.push("| --- | ------ | -------- | -------------- | ------- |");
  } else {
    lines.push("| URL | Status | Findings | Top categories |");
    lines.push("| --- | ------ | -------- | -------------- |");
  }
  for (const row of report) {
    const status = row.error ? `\u26A0\uFE0F error` : row.ok ? "\u2705" : "\u274C";
    const top = topCategories(row.categories);
    const cellUrl = `[${shortenUrl(row.url)}](${row.url})`;
    const cells = [cellUrl, status, String(row.findings), top || "\u2014"];
    if (anyImage) {
      cells.push(row.imageUrl ? `<a href="${row.imageUrl}"><img src="${row.imageUrl}" width="120" alt="preview" /></a>` : "\u2014");
    }
    lines.push(`| ${cells.join(" | ")} |`);
  }
  if (report.some((r) => r.error)) {
    lines.push("");
    lines.push("> Some URLs returned an error \u2014 see the workflow logs for details.");
  }
  lines.push("");
  lines.push(`<sub>Generated by [ScreenshotsMCP CLI](https://www.screenshotmcp.com).</sub>`);
  return lines.join("\n");
}

/**
 * Renders a self-contained, no-dependency HTML report. Inline CSS keeps it
 * usable as a build artifact you can email or attach to a CI run without any
 * external assets.
 */
export function renderHtmlReport(report: UrlReport[], ctx: ReportContext): string {
  const verdict = ctx.pass ? "Passed" : "Failed";
  const verdictClass = ctx.pass ? "ok" : "fail";
  const generated = new Date().toLocaleString();
  const rows = report
    .map((row) => {
      const status = row.error ? "error" : row.ok ? "ok" : "fail";
      const top = topCategoriesPlain(row.categories);
      const preview = row.imageUrl
        ? `<a href="${escapeHtml(row.imageUrl)}" target="_blank" rel="noopener"><img src="${escapeHtml(row.imageUrl)}" alt="preview" /></a>`
        : "&mdash;";
      return `
        <tr class="status-${status}">
          <td><a href="${escapeHtml(row.url)}" target="_blank" rel="noopener">${escapeHtml(shortenUrl(row.url))}</a></td>
          <td><span class="badge badge-${status}">${status === "ok" ? "PASS" : status === "fail" ? "FAIL" : "ERROR"}</span></td>
          <td class="num">${row.findings}</td>
          <td>${top || "&mdash;"}</td>
          <td class="preview">${preview}</td>
        </tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>ScreenshotsMCP Audit Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 32px; background: #f8fafc; color: #0f172a; }
    h1 { margin: 0 0 8px; font-size: 24px; }
    .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin: 24px 0; }
    .stat { background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 16px; }
    .stat .label { font-size: 11px; text-transform: uppercase; color: #64748b; letter-spacing: 0.05em; }
    .stat .value { font-size: 20px; font-weight: 600; margin-top: 4px; }
    .verdict { display: inline-block; padding: 4px 12px; border-radius: 999px; font-weight: 600; font-size: 13px; }
    .verdict.ok { background: #dcfce7; color: #166534; }
    .verdict.fail { background: #fee2e2; color: #991b1b; }
    table { width: 100%; border-collapse: collapse; background: white; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; }
    th, td { text-align: left; padding: 12px 14px; border-bottom: 1px solid #e2e8f0; vertical-align: middle; }
    th { background: #f1f5f9; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #475569; }
    tr:last-child td { border-bottom: none; }
    td.num { font-variant-numeric: tabular-nums; font-weight: 600; }
    td.preview img { width: 120px; height: auto; border-radius: 4px; border: 1px solid #e2e8f0; cursor: zoom-in; display: block; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
    .badge-ok { background: #dcfce7; color: #166534; }
    .badge-fail { background: #fee2e2; color: #991b1b; }
    .badge-error { background: #fef3c7; color: #854d0e; }
    .footer { margin-top: 32px; color: #94a3b8; font-size: 12px; }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <h1>ScreenshotsMCP Audit Report <span class="verdict ${verdictClass}">${verdict}</span></h1>
  <div class="meta">Generated ${escapeHtml(generated)}${ctx.budgetSource ? ` &middot; Budget: ${escapeHtml(ctx.budgetSource)}` : ""}</div>
  <div class="stats">
    <div class="stat"><div class="label">URLs Audited</div><div class="value">${report.length}</div></div>
    <div class="stat"><div class="label">Total Findings</div><div class="value">${ctx.totalFindings} <span style="font-size:13px; color:#64748b;">/ ${ctx.maxTotal}</span></div></div>
    <div class="stat"><div class="label">URLs Over Limit</div><div class="value">${countFailed(report)} <span style="font-size:13px; color:#64748b;">(per-URL ${ctx.maxPer})</span></div></div>
  </div>
  <table>
    <thead>
      <tr><th>URL</th><th>Status</th><th>Findings</th><th>Top Categories</th><th>Preview</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by <a href="https://www.screenshotmcp.com" target="_blank" rel="noopener">ScreenshotsMCP</a> CLI.</div>
</body>
</html>`;
}

function topCategoriesPlain(categories: Record<string, number>, limit = 3): string {
  return Object.entries(categories)
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([cat, n]) => `<code>${escapeHtml(cat)}</code> ${n}`)
    .join(" &middot; ");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Renders a one-line summary suitable for status-check titles.
 */
export function renderShortSummary(report: UrlReport[], ctx: ReportContext): string {
  const failed = countFailed(report);
  const verdict = ctx.pass ? "passed" : "failed";
  return `${ctx.totalFindings} findings across ${report.length} URLs (${failed} over per-URL limit) \u2014 ${verdict}`;
}

function countFailed(report: UrlReport[]): number {
  return report.filter((r) => !r.ok).length;
}

function topCategories(categories: Record<string, number>, limit = 3): string {
  return Object.entries(categories)
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([cat, n]) => `\`${cat}\` ${n}`)
    .join(" \u00b7 ");
}

function shortenUrl(url: string): string {
  try {
    const u = new URL(url);
    const base = u.host + u.pathname;
    return base.length > 50 ? base.slice(0, 47) + "\u2026" : base;
  } catch {
    return url;
  }
}
