/**
 * Pure formatters for `screenshotsmcp check` reports.
 * Kept separate so they're easy to unit-test and so `check.ts` stays focused
 * on orchestration.
 */

export interface UrlReport {
  url: string;
  ok: boolean;
  findings: number;
  categories: Record<string, number>;
  error?: string;
}

export interface ReportContext {
  totalFindings: number;
  maxPer: number;
  maxTotal: number;
  pass: boolean;
  budgetSource?: string;
}

/**
 * Renders a markdown summary suitable for GitHub Actions comments or PR
 * descriptions. Includes a verdict header, a stat block, and a per-URL table.
 */
export function renderGithubComment(report: UrlReport[], ctx: ReportContext): string {
  const verdict = ctx.pass ? "\u2705 Passed" : "\u274C Failed";
  const lines: string[] = [];
  lines.push(`### ScreenshotsMCP audit \u2014 ${verdict}`);
  lines.push("");
  lines.push(`- **${report.length}** URL${report.length === 1 ? "" : "s"} audited`);
  lines.push(`- **${ctx.totalFindings}** total findings (limit \`${ctx.maxTotal}\`)`);
  lines.push(`- **${countFailed(report)}** URL${countFailed(report) === 1 ? "" : "s"} over the per-URL limit (\`${ctx.maxPer}\`)`);
  if (ctx.budgetSource) {
    lines.push(`- Budget loaded from \`${ctx.budgetSource}\``);
  }
  lines.push("");
  lines.push("| URL | Status | Findings | Top categories |");
  lines.push("| --- | ------ | -------- | -------------- |");
  for (const row of report) {
    const status = row.error ? `\u26A0\uFE0F error` : row.ok ? "\u2705" : "\u274C";
    const top = topCategories(row.categories);
    const cellUrl = `[${shortenUrl(row.url)}](${row.url})`;
    lines.push(`| ${cellUrl} | ${status} | ${row.findings} | ${top || "\u2014"} |`);
  }
  if (report.some((r) => r.error)) {
    lines.push("");
    lines.push("> Some URLs returned an error \u2014 see the workflow logs for details.");
  }
  lines.push("");
  lines.push(`<sub>Generated by [ScreenshotsMCP CLI](https://www.screenshotmcp.com).</sub>`);
  return lines.join("\n");
}

/**
 * Renders a one-line summary suitable for status-check titles.
 */
export function renderShortSummary(report: UrlReport[], ctx: ReportContext): string {
  const failed = countFailed(report);
  const verdict = ctx.pass ? "passed" : "failed";
  return `${ctx.totalFindings} findings across ${report.length} URLs (${failed} over per-URL limit) \u2014 ${verdict}`;
}

function countFailed(report: UrlReport[]): number {
  return report.filter((r) => !r.ok).length;
}

function topCategories(categories: Record<string, number>, limit = 3): string {
  return Object.entries(categories)
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([cat, n]) => `\`${cat}\` ${n}`)
    .join(" \u00b7 ");
}

function shortenUrl(url: string): string {
  try {
    const u = new URL(url);
    const base = u.host + u.pathname;
    return base.length > 50 ? base.slice(0, 47) + "\u2026" : base;
  } catch {
    return url;
  }
}
